--- #YAML:1.0
name:               Win32-API
version:            0.75
abstract:           Perl Win32 API Import Facility
author:
    - Aldo Calpini <dada@perl.it>, Cosimo Streppone <cosimo@cpan.org>, Daniel Dragan <bulkdd@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Encode:          0
    File::Spec:      0
    IPC::Open3:      0
    Math::Int64:     0
    Test::More:      0
    Win32:           0
    Win32API::File:  0
requires:
    perl:          5
    Scalar::Util:  0
resources:
    repository:  https://github.com/cosimo/perl5-win32-api
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
keywords:
    - win32
    - api
    - dll
    - libraries
recommends:
    Math::Int64:  0
